spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lab_rescheduling_system
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:mySuperSecretKeyThatIsLongEnough123}
    expiration: 86400000
  upload:
    dir: uploads


logging:
  level:
    com.uor.engineering: DEBUG